parameters:
  featurefactory:
    catalog: "hive_metastore"
    database: "odap_features_{entity}"
    features:
      latest_table: "latest"

    metadata:
      table: "metadata"
      
    #ids:
    #  table: "catalog.db.ids_table"

    entities:
        user:
        id_column: "user_id"
        id_column_type: "string"

  segmentfactory:
    catalog: "hive_metastore"
    database: "odap_segments"
    log:
      table: "export_log"

    segment:
      table: "segment_log"

    destinations:
      your_destination:
        type: "your_destination_type"

  usecasefactory:
    catalog: "hive_metastore"
    database: "odap_use_cases"
    table: "use_cases"
