parameters:
  featurefactory:
    environment: "prod"

    catalog: "hive_metastore"
    database: "odap_features_{entity}_%environment%"
    # featurestorebundle.db_name: '%kernel.environment%_feature_store' # 'old' config
    features:
      latest_table: "latest"

    metadata:
      table: "metadata"
      
    entities:
        user:
          id_column: "user_id"
          id_column_type: "string"

    # checkpoint_dir: "dbfs:/mnt/aam-cpex-prod/gold/feature_store/checkpoints"
    # checkpoint_dir: "dbfs:/mnt/aam-cpex-%parameters.featurefactory.environment%/gold/feature_store/checkpoints"
    checkpoint_dir: "dbfs:/mnt/aam-cpex-dev/solutions/mt-test/checkpoints"
    # featurestorebundle.checkpoint.default_checkpoint_dir: '/mnt/aam-cpex-%kernel.environment%/gold/feature_store/checkpoints' # 'old' config
    checkpoint_interval: 5


  segmentfactory:
    catalog: "hive_metastore"
    database: "odap_segments"
    log:
      table: "export_log"

    segment:
      table: "segment_log"

    destinations:
      your_destination:
        type: "your_destination_type"

  usecasefactory:
    catalog: "hive_metastore"
    database: "odap_use_cases"
    table: "use_cases"
