paths:
  sdm_table_paths:
    sdm_preprocessed: "/mnt/aam-cpex-dev/solutions/testing/sdm_preprocessed.delta"
    sdm_browser: "/mnt/aam-cpex-dev/solutions/testing/sdm_browser.delta"
    sdm_device: "/mnt/aam-cpex-dev/solutions/testing/sdm_device.delta"
    sdm_os: "/mnt/aam-cpex-dev/solutions/testing/sdm_os.delta"
    sdm_url: "/mnt/aam-cpex-dev/solutions/testing/sdm_url.delta"
    sdm_session: "/mnt/aam-cpex-dev/solutions/testing/sdm_session.delta"
    sdm_pageview: "/mnt/aam-cpex-dev/solutions/testing/sdm_pageview.delta"
    sdm_tokenized_domains: "/mnt/aam-cpex-dev/solutions/testing/sdm_tokenized_domains.delta"
    sdm_sociodemo_targets: "/mnt/aam-cpex-dev/solutions/testing/sdm_sociodemo_targets.delta"

  piano_table_paths:
    cpex_table_piano: "/mnt/aam-cpex-dev/solutions/testing/cpex_piano.delta"
    cpex_table_short_piano: "/mnt/aam-cpex-dev/solutions/testing/cpex_piano_short.delta"

  user_table_paths:
    user_traits: "/mnt/aam-cpex-dev/solutions/testing/user_traits.delta"
    user_segments: "/mnt/aam-cpex-dev/solutions/testing/user_segments.delta"

  interests_table_paths:
    interests_definition: "/mnt/aam-cpex-dev/solutions/testing/interests_definition.delta"




jobs_config:
  regular_optimization:
    keep_history_n_days: 21
    vacuum_n_hours: 240
    tables_options:
      bronze.cpex_piano:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'day'
      silver.cpex_aam_cleansed:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'day'
      silver.sdm_session:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'session_date'
      silver.sdm_pageview:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'page_screen_view_date'
      silver.sdm_url:
        vacuum: True
        optimize: True
        keep_history: False
      silver.sdm_sociodemo_targets:
        vacuum: True
        optimize: False
        keep_history: False
      silver.user_traits:
        vacuum: True
        optimize: False
        keep_history: False
      silver.user_segments:
        vacuum: True
        optimize: False
        keep_history: False
      silver.sdm_preprocessed:
        vacuum: True
        optimize: False
        keep_history: False
      silver.income_interest_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.income_url_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.income_other_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.education_interest_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.education_url_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.education_other_scores:
        vacuum: True
        optimize: False
        keep_history: False

tables_options:
    series_length:
      n_hours_short: 72
      
