paths:
  sdm_preprocessed: "/mnt/aam-cpex-dev/solutions/testing/sdm_preprocessed.delta"
  sdm_browser: "/mnt/aam-cpex-dev/solutions/testing/sdm_browser.delta"
  sdm_device: "/mnt/aam-cpex-dev/solutions/testing/sdm_device.delta"
  sdm_os: "/mnt/aam-cpex-dev/solutions/testing/sdm_os.delta"
  sdm_url: "/mnt/aam-cpex-dev/solutions/testing/sdm_url.delta"
  sdm_session: "/mnt/aam-cpex-dev/solutions/testing/sdm_session.delta"
  sdm_pageview: "/mnt/aam-cpex-dev/solutions/testing/sdm_pageview.delta"
  sdm_tokenized_domains: "/mnt/aam-cpex-dev/solutions/testing/sdm_tokenized_domains.delta"
  sdm_sociodemo_targets: "/mnt/aam-cpex-dev/solutions/testing/sdm_sociodemo_targets.delta"

  cpex_table_piano: "/mnt/aam-cpex-dev/solutions/testing/cpex_piano.delta"
  cpex_table_short_piano: "/mnt/aam-cpex-dev/solutions/testing/cpex_piano_short.delta"

  user_segments_path: "/mnt/aam-cpex-dev/solutions/testing/user_segments_piano.delta"
  lookalike_path: "/mnt/aam-cpex-dev/silver/lookalike/lookalike.delta"

  interests_definition: "/mnt/aam-cpex-dev/silver/interests/interests_definition.delta"
  
  income_url_scores: "/mnt/aam-cpex-dev/silver/income/income_url_scores.delta"
  income_url_coeffs: "/mnt/aam-cpex-dev/silver/income/income_url_coeffs.delta"
  income_interest_scores: "/mnt/aam-cpex-dev/silver/income/income_interest_scores.delta"
  income_interest_coeffs: "/mnt/aam-cpex-dev/silver/income/income_interest_coeffs.delta"
  income_other_scores: "/mnt/aam-cpex-dev/silver/income/income_other_scores.delta"
  income_other_coeffs: "/mnt/aam-cpex-dev/silver/income/income_other_coeffs.delta"
    
  education_interest_scores: "/mnt/aam-cpex-dev/silver/education/education_interest_scores.delta"
  education_interest_coeffs: "/mnt/aam-cpex-dev/silver/education/education_interest_coeffs.delta"
  education_url_scores: "/mnt/aam-cpex-dev/silver/education/education_url_scores.delta"
  education_url_coeffs: "/mnt/aam-cpex-dev/silver/education/education_url_coeffs.delta"
  education_other_scores: "/mnt/aam-cpex-dev/silver/education/education_other_scores.delta"
  education_other_coeffs: "/mnt/aam-cpex-dev/silver/education/education_other_coeffs.delta"

  location_traits_map: "/mnt/aam-cpex-dev/silver/location/location_traits_map.delta"


  models:
    sociodemo:
      dev:
        ageGroup_0_17: 'dbfs:/databricks/mlflow-tracking/3954795528263881/d8ecf6ea998c433e9ba8021fe5795ed5/artifacts/model_age_LogReg_0'
        ageGroup_18_24: 'dbfs:/databricks/mlflow-tracking/3954795528263881/d8ecf6ea998c433e9ba8021fe5795ed5/artifacts/model_age_LogReg_1'
        ageGroup_25_34: 'dbfs:/databricks/mlflow-tracking/3954795528263881/d8ecf6ea998c433e9ba8021fe5795ed5/artifacts/model_age_LogReg_2'
        ageGroup_35_44: 'dbfs:/databricks/mlflow-tracking/3954795528263881/d8ecf6ea998c433e9ba8021fe5795ed5/artifacts/model_age_LogReg_3'
        ageGroup_45_54: 'dbfs:/databricks/mlflow-tracking/3954795528263881/d8ecf6ea998c433e9ba8021fe5795ed5/artifacts/model_age_LogReg_4'
        ageGroup_55_64: 'dbfs:/databricks/mlflow-tracking/3954795528263881/d8ecf6ea998c433e9ba8021fe5795ed5/artifacts/model_age_LogReg_5'
        ageGroup_65_100: 'dbfs:/databricks/mlflow-tracking/3954795528263881/d8ecf6ea998c433e9ba8021fe5795ed5/artifacts/model_age_LogReg_6'
        gender_male: 'dbfs:/databricks/mlflow-tracking/3954795528264193/73d32166c9e04c0594775e0397dc0031/artifacts/model_gender_Logreg'

jobs_config:
  regular_optimization:
    keep_history_n_days: 7
    vacuum_n_hours: 240
    tables_options:
      cpex_table_piano:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'day'
      sdm_session:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'session_date'
      sdm_pageview:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'page_screen_view_date'
      sdm_url:
        vacuum: True
        optimize: True
        keep_history: False
      sdm_sociodemo_targets:
        vacuum: True
        optimize: False
        keep_history: False
      user_segments_path:
        vacuum: True
        optimize: False
        keep_history: False
      sdm_preprocessed:
        vacuum: True
        optimize: False
        keep_history: False
      income_interest_scores:
        vacuum: True
        optimize: False
        keep_history: False
      income_url_scores:
        vacuum: True
        optimize: False
        keep_history: False
      income_other_scores:
        vacuum: True
        optimize: False
        keep_history: False
      education_interest_scores:
        vacuum: True
        optimize: False
        keep_history: False
      education_url_scores:
        vacuum: True
        optimize: False
        keep_history: False
      education_other_scores:
        vacuum: True
        optimize: False
        keep_history: False

featurestorebundle:
  db_name: '%kernel.environment%_feature_store'
  base_path: '%feature_store.base_path%'
  checkpoint:
    default_checkpoint_dir: '/mnt/aam-cpex-%kernel.environment%/gold/feature_store/checkpoints'
  feature:
    table:
      name_template: 'features_{entity}'
      path_template: '%featurestorebundle.base_path%/features/{entity}.delta'
    backend: 'delta_path'
  metadata:
    backend: 'delta_path'
  target:
    table:
      name_template: 'targets_{entity}'
      path_template: '%feature_store.base_path%/target/{entity}.delta'
    enum_table:
      name: 'targets_enum'
      path: '%feature_store.base_path%/target/targets_enum.delta'
    backend: 'delta_path'
  entities:
    user_entity:
      id_column: "user_id"
      id_column_type: "string"
  entity_time_column: "timestamp"
  widgets:
    defaults:
      timestamp: "2020-12-12"
      use_bigrams: "false"
      tokens_version: "cleaned_unique"
  time_windows: ["7d"]

  checkpointing:
    base_dir: '/mnt/aam-cpex-%kernel.environment%/gold/feature_store/checkpoints'

tables_options:
  series_length:
    n_hours_short: 72

web_features_list:
 - web_analytics_device_os_last_used_7d
 - web_analytics_channel_device_count_distinct_7d
 - web_analytics_mobile_user_7d
 - web_analytics_smart_tv_user_7d
 - web_analytics_web_active_7d
 - web_analytics_device_type_most_common_7d
 - owner_names_7d
 - web_analytics_total_visits_7d
 - web_analytics_device_browser_most_common_7d
 - web_analytics_device_browser_last_used_7d
 - web_analytics_blog_days_since_last_visit_7d
 - web_analytics_visit_time_most_common_7d
 - web_analytics_device_type_last_used_7d
 - web_analytics_device_os_most_common_7d
 - web_analytics_pageviews_sum_7d
 - web_analytics_time_on_site_avg_7d
 - web_analytics_web_security_affinity_7d
 - web_analytics_desktop_user_7d
 - web_analytics_num_distinct_device_categories_7d
 - web_analytics_tablet_user_7d
 - web_analytics_page_search_engine_most_common_7d
 - web_analytics_page_search_engine_last_used_7d

