paths:
  sdm_table_paths:
    sdm_preprocessed: "/mnt/aam-cpex-dev/solutions/testing/sdm_preprocessed.delta"
    sdm_browser: "/mnt/aam-cpex-dev/solutions/testing/sdm_browser.delta"
    sdm_device: "/mnt/aam-cpex-dev/solutions/testing/sdm_device.delta"
    sdm_os: "/mnt/aam-cpex-dev/solutions/testing/sdm_os.delta"
    sdm_url: "/mnt/aam-cpex-dev/solutions/testing/sdm_url.delta"
    sdm_session: "/mnt/aam-cpex-dev/solutions/testing/sdm_session.delta"
    sdm_pageview: "/mnt/aam-cpex-dev/solutions/testing/sdm_pageview.delta"
    sdm_tokenized_domains: "/mnt/aam-cpex-dev/solutions/testing/sdm_tokenized_domains.delta"
    sdm_sociodemo_targets: "/mnt/aam-cpex-dev/solutions/testing/sdm_sociodemo_targets.delta"

  piano_table_paths:
    cpex_table_piano: "/mnt/aam-cpex-dev/solutions/testing/cpex_piano.delta"
    cpex_table_short_piano: "/mnt/aam-cpex-dev/solutions/testing/cpex_piano_short.delta"

  user_table_paths:
    user_traits: "/mnt/aam-cpex-dev/solutions/testing/user_traits.delta"
    user_segments: "/mnt/aam-cpex-dev/solutions/testing/user_segments.delta"

  interests_table_paths:
    interests_definition: "/mnt/aam-cpex-dev/silver/interests/interests_definition.delta"
  
  income_table_paths:
    income_url_scores: "/mnt/aam-cpex-dev/silver/income/income_url_scores.delta"
    income_interest_scores: "/mnt/aam-cpex-dev/silver/income/income_interest_scores.delta"
    income_other_scores: "/mnt/aam-cpex-dev/silver/income/income_other_scores.delta"

  education_table_paths:
    education_interest_scores: "/mnt/aam-cpex-dev/silver/education/education_interest_scores.delta"
    education_url_scores: "/mnt/aam-cpex-dev/silver/education/education_url_scores.delta"
    education_other_scores: "/mnt/aam-cpex-dev/silver/education/education_other_scores.delta"

jobs_config:
  regular_optimization:
    keep_history_n_days: 7
    vacuum_n_hours: 240
    tables_options:
      bronze.cpex_piano:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'day'
      silver.cpex_aam_cleansed:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'day'
      silver.sdm_session:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'session_date'
      silver.sdm_pageview:
        vacuum: True
        optimize: True
        keep_history: True
        date_column: 'page_screen_view_date'
      silver.sdm_url:
        vacuum: True
        optimize: True
        keep_history: False
      silver.sdm_sociodemo_targets:
        vacuum: True
        optimize: False
        keep_history: False
      silver.user_traits:
        vacuum: True
        optimize: False
        keep_history: False
      silver.user_segments:
        vacuum: True
        optimize: False
        keep_history: False
      silver.sdm_preprocessed:
        vacuum: True
        optimize: False
        keep_history: False
      silver.income_interest_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.income_url_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.income_other_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.education_interest_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.education_url_scores:
        vacuum: True
        optimize: False
        keep_history: False
      silver.education_other_scores:
        vacuum: True
        optimize: False
        keep_history: False

featurestorebundle:
  db_name: '%kernel.environment%_feature_store'
  base_path: '%feature_store.base_path%'
  checkpoint:
    default_checkpoint_dir: '/mnt/aam-cpex-%kernel.environment%/gold/feature_store/checkpoints'
  feature:
    table:
      name_template: 'features_{entity}'
      path_template: '%featurestorebundle.base_path%/features/{entity}.delta'
    backend: 'delta_path'
  metadata:
    backend: 'delta_path'
  target:
    table:
      name_template: 'targets_{entity}'
      path_template: '%feature_store.base_path%/target/{entity}.delta'
    enum_table:
      name: 'targets_enum'
      path: '%feature_store.base_path%/target/targets_enum.delta'
    backend: 'delta_path'
  entities:
    user_entity:
      id_column: "user_id"
      id_column_type: "string"
  widgets:
    defaults:
      timestamp: "2020-12-12"
      use_bigrams: "false"
      tokens_version: "cleaned_unique"
  time_windows: ["7d"]

  checkpointing:
    base_dir: '/mnt/aam-cpex-%kernel.environment%/gold/feature_store/checkpoints'

tables_options:
  series_length:
    n_hours_short: 72
