# Databricks notebook source
# MAGIC %md #Preparation of feature store

# COMMAND ----------

import yaml

# COMMAND ----------

config_path = "../config.yaml"

with open(config_path, "r", encoding="utf-8") as cf:
    config_content = yaml.load(cf, Loader=yaml.FullLoader)["parameters"]

# COMMAND ----------

fs_environment = config_content["featurefactory"]["environment"]
path_to_fs = "dbfs:/mnt/aam-cpex-dev/solutions/mt-test"

fs_entities = config_content["featurefactory"]["entities"]
fs_entity = next(iter(fs_entities))

fs_database = config_content["featurefactory"]["database"]

# COMMAND ----------

# MAGIC %md ## Database

# COMMAND ----------

database_name = fs_database.replace("{entity}", fs_entity).replace(r"%environment%", fs_environment)

# COMMAND ----------

res = spark.sql(f"""CREATE DATABASE IF NOT EXISTS {database_name}""")
display(res)

# COMMAND ----------

# MAGIC %md ##Tables

# COMMAND ----------

# MAGIC %md ###FS latest

# COMMAND ----------

res = spark.sql(f"""
CREATE TABLE IF NOT EXISTS hive_metastore.{database_name}.latest (
  user_id STRING,
  web_analytics_device_type_most_common_7d STRING,
  web_analytics_device_type_last_used_7d STRING,
  web_analytics_device_browser_most_common_7d STRING,
  web_analytics_device_browser_last_used_7d STRING,
  web_analytics_device_os_most_common_7d STRING,
  web_analytics_device_os_last_used_7d STRING,
  web_analytics_num_distinct_device_categories_7d BIGINT,
  web_analytics_channel_device_count_distinct_7d BIGINT,
  web_analytics_visit_time_most_common_7d STRING,
  web_analytics_mobile_user_7d DOUBLE,
  web_analytics_desktop_user_7d DOUBLE,
  web_analytics_smart_tv_user_7d DOUBLE,
  web_analytics_tablet_user_7d DOUBLE,
  web_analytics_time_on_site_avg_7d DOUBLE,
  web_analytics_web_active_7d INT,
  web_analytics_web_security_affinity_7d DOUBLE,
  web_analytics_page_search_engine_most_common_7d STRING,
  web_analytics_page_search_engine_last_used_7d STRING,
  web_analytics_pageviews_sum_7d BIGINT,
  owner_names_7d STRING,
  web_analytics_total_visits_7d BIGINT,
  web_analytics_blog_days_since_last_visit_7d INT,
  ad_interest_affinity_allergy DOUBLE,
  ad_interest_affinity_convertible DOUBLE,
  ad_interest_affinity_weight_loss DOUBLE,
  ad_interest_affinity_golf DOUBLE,
  ad_interest_affinity_clothing DOUBLE,
  ad_interest_affinity_remodeling_and_construction DOUBLE,
  ad_interest_affinity_photography DOUBLE,
  ad_interest_affinity_buying_or_selling_homes DOUBLE,
  ad_interest_affinity_asia DOUBLE,
  ad_interest_affinity_panic_or_anxiety_disorders DOUBLE,
  ad_interest_affinity_buying_or_selling_cars DOUBLE,
  ad_interest_affinity_motorcycles DOUBLE,
  ad_interest_affinity_elementary_school DOUBLE,
  ad_interest_affinity_pro_ice_hockey DOUBLE,
  ad_interest_affinity_australia_and_new_zealand DOUBLE,
  ad_interest_affinity_politics DOUBLE,
  ad_interest_affinity_video_and_computer_games DOUBLE,
  ad_interest_affinity_it_decision_makers DOUBLE,
  ad_interest_affinity_parenting DOUBLE,
  ad_interest_affinity_telecommuting DOUBLE,
  ad_interest_affinity_job_search DOUBLE,
  ad_interest_affinity_interior_decorating DOUBLE,
  ad_interest_affinity_high_school_students DOUBLE,
  ad_interest_affinity_pregnancy DOUBLE,
  ad_interest_affinity_animation DOUBLE,
  ad_interest_affinity_computer_reviews DOUBLE,
  ad_interest_affinity_traveling_with_kids DOUBLE,
  ad_interest_affinity_3_d_graphics DOUBLE,
  ad_interest_affinity_books_and_literature DOUBLE,
  ad_interest_affinity_board_games_or_puzzles DOUBLE,
  ad_interest_affinity_green_solutions DOUBLE,
  ad_interest_affinity_depression DOUBLE,
  ad_interest_affinity_gardening DOUBLE,
  ad_interest_affinity_cell_phones DOUBLE,
  ad_interest_affinity_college_life DOUBLE,
  ad_interest_affinity_local_news DOUBLE,
  ad_interest_affinity_financial_aid DOUBLE,
  ad_interest_affinity_guitar DOUBLE,
  ad_interest_affinity_canada DOUBLE,
  ad_interest_affinity_business_travel DOUBLE,
  ad_interest_affinity_insurance DOUBLE,
  ad_interest_affinity_south_america DOUBLE,
  ad_interest_affinity_performance_vehicles DOUBLE,
  ad_interest_affinity_agriculture DOUBLE,
  ad_interest_affinity_cigars DOUBLE,
  ad_interest_affinity_coffee_lovers DOUBLE,
  ad_interest_affinity_mens_health DOUBLE,
  ad_interest_affinity_dining_out DOUBLE,
  ad_interest_affinity_comic_books DOUBLE,
  ad_interest_affinity_mexico_and_central_america DOUBLE,
  ad_interest_affinity_hedge_fund DOUBLE,
  ad_interest_affinity_environmental_safety DOUBLE,
  ad_interest_affinity_humor DOUBLE,
  ad_interest_affinity_cold_and_flu DOUBLE,
  ad_interest_affinity_fashion DOUBLE,
  ad_interest_affinity_hr_software DOUBLE,
  ad_interest_affinity_financial_news DOUBLE,
  ad_interest_affinity_olympics DOUBLE,
  ad_interest_affinity_university_students DOUBLE,
  ad_interest_affinity_bodybuilding DOUBLE,
  ad_interest_affinity_generation_z DOUBLE,
  ad_interest_affinity_betting DOUBLE,
  ad_interest_affinity_astrology DOUBLE,
  ad_interest_affinity_teens DOUBLE,
  ad_interest_affinity_art_or_technology DOUBLE,
  ad_interest_affinity_fotovoltaics DOUBLE,
  ad_interest_affinity_dogs DOUBLE,
  ad_interest_affinity_fine_art DOUBLE,
  ad_interest_affinity_italy DOUBLE,
  ad_interest_affinity_cats DOUBLE,
  ad_interest_affinity_skateboarding DOUBLE,
  ad_interest_affinity_auto_parts DOUBLE,
  ad_interest_affinity_international_news DOUBLE,
  ad_interest_affinity_jewelry DOUBLE,
  ad_interest_affinity_advertising DOUBLE,
  ad_interest_affinity_diabetes DOUBLE,
  ad_interest_affinity_wine DOUBLE,
  ad_interest_affinity_b2b_small_and_midsize_business_osvc DOUBLE,
  ad_interest_affinity_weather DOUBLE,
  ad_interest_affinity_barbecues_and_grilling DOUBLE,
  ad_interest_affinity_vegan DOUBLE,
  ad_interest_affinity_energy_crisis DOUBLE,
  ad_interest_affinity_deal_hunters DOUBLE,
  ad_interest_affinity_christmas_shopping DOUBLE,
  ad_interest_affinity_trucks_and_accessories DOUBLE,
  ad_interest_affinity_movies DOUBLE,
  ad_interest_affinity_english_as_a_2nd_language DOUBLE,
  ad_interest_affinity_gay_life DOUBLE,
  ad_interest_affinity_cameras_and_camcorders DOUBLE,
  ad_interest_affinity_home_repair DOUBLE,
  ad_interest_affinity_radio DOUBLE,
  ad_interest_affinity_climbing DOUBLE,
  ad_interest_affinity_human_resources DOUBLE,
  ad_interest_affinity_music DOUBLE,
  ad_interest_affinity_celebrity_fan_or_gossip DOUBLE,
  ad_interest_affinity_football DOUBLE,
  ad_interest_affinity_exotic_pets DOUBLE,
  ad_interest_affinity_senior_living DOUBLE,
  ad_interest_affinity_data_centers DOUBLE,
  ad_interest_affinity_europe DOUBLE,
  ad_interest_affinity_usa DOUBLE,
  ad_interest_affinity_pro_basketball DOUBLE,
  ad_interest_affinity_mother_with_toddlers DOUBLE,
  ad_interest_affinity_credit_or_debt_and_loans DOUBLE,
  ad_interest_affinity_dating DOUBLE,
  ad_interest_affinity_electric_vehicle DOUBLE,
  ad_interest_affinity_internet_technology DOUBLE,
  ad_interest_affinity_b2b_big_corporations_managers_decision_makers DOUBLE,
  ad_interest_affinity_formule_1 DOUBLE,
  ad_interest_affinity_young_families_with_children DOUBLE,
  ad_interest_affinity_architects DOUBLE,
  ad_interest_affinity_boxing DOUBLE,
  ad_interest_affinity_womens_health DOUBLE,
  ad_interest_affinity_divorce_support DOUBLE,
  ad_interest_affinity_exotic_vacation DOUBLE,
  ad_interest_affinity_tattoos DOUBLE,
  ad_interest_affinity_luxury_vehicle DOUBLE,
  ad_interest_affinity_investments DOUBLE,
  ad_interest_affinity_middle_class_vehicle DOUBLE,
  ad_interest_affinity_suv_vehicle DOUBLE,
  ad_interest_affinity_eye_make_up DOUBLE,
  ad_interest_affinity_make_up DOUBLE,
  ad_interest_affinity_beauty DOUBLE,
  ad_interest_affinity_education DOUBLE,
  ad_interest_affinity_science DOUBLE,
  ad_interest_affinity_family_and_parenting DOUBLE,
  ad_interest_affinity_sports DOUBLE,
  ad_interest_affinity_careers DOUBLE,
  ad_interest_affinity_travel DOUBLE,
  ad_interest_affinity_real_estate DOUBLE,
  ad_interest_affinity_pets DOUBLE,
  ad_interest_affinity_society DOUBLE,
  ad_interest_affinity_shopping DOUBLE,
  ad_interest_affinity_home_and_garden DOUBLE,
  ad_interest_affinity_automotive DOUBLE,
  ad_interest_affinity_personal_finance DOUBLE,
  ad_interest_affinity_business DOUBLE,
  ad_interest_affinity_law_govt_and_politics DOUBLE,
  ad_interest_affinity_b2b DOUBLE,
  ad_interest_affinity_food_and_drink DOUBLE,
  ad_interest_affinity_health_and_fitness DOUBLE,
  ad_interest_affinity_arts_and_entertainment DOUBLE,
  ad_interest_affinity_hobbies_and_interests DOUBLE,
  ad_interest_affinity_style_and_fashion DOUBLE,
  ad_interest_affinity_technology_and_computing DOUBLE,
  ad_interest_affinity_news DOUBLE,
  ad_interest_affinity_home_tech_equipment DOUBLE,
  ad_interest_affinity_bathrooms DOUBLE,
  ad_interest_affinity_distillates DOUBLE,
  income_model_score_low DOUBLE,
  income_model_score_mid DOUBLE,
  income_model_score_high DOUBLE,
  income_model_perc_low DOUBLE,
  income_model_perc_mid DOUBLE,
  income_model_perc_high DOUBLE,
  edu_model_score_zs DOUBLE,
  edu_model_score_ss_no DOUBLE,
  edu_model_score_ss_yes DOUBLE,
  edu_model_score_vs DOUBLE,
  edu_model_perc_zs DOUBLE,
  edu_model_perc_ss_no DOUBLE,
  edu_model_perc_ss_yes DOUBLE,
  edu_model_perc_vs DOUBLE,
  sociodemo_prob_agegroup_0_17 DOUBLE,
  sociodemo_perc_agegroup_0_17 DOUBLE,
  sociodemo_prob_agegroup_18_24 DOUBLE,
  sociodemo_perc_agegroup_18_24 DOUBLE,
  sociodemo_prob_agegroup_25_34 DOUBLE,
  sociodemo_perc_agegroup_25_34 DOUBLE,
  sociodemo_prob_agegroup_35_44 DOUBLE,
  sociodemo_perc_agegroup_35_44 DOUBLE,
  sociodemo_prob_agegroup_45_54 DOUBLE,
  sociodemo_perc_agegroup_45_54 DOUBLE,
  sociodemo_prob_agegroup_55_64 DOUBLE,
  sociodemo_perc_agegroup_55_64 DOUBLE,
  sociodemo_prob_agegroup_65_100 DOUBLE,
  sociodemo_perc_agegroup_65_100 DOUBLE,
  sociodemo_prob_gender_male DOUBLE,
  sociodemo_perc_gender_male DOUBLE,
  sociodemo_perc_gender_female DOUBLE,
  sociodemo_prob_gender_female DOUBLE,
  sociodemo_targets_age STRING,
  sociodemo_targets_gender STRING,
  lookalike_targets STRING,
  lookalike_prob_dmp_aa9bqvteomrl_cpex DOUBLE,
  lookalike_perc_dmp_aa9bqvteomrl_cpex DOUBLE,
  lookalike_prob_dmp_aa9bom9sdj6m_cpex DOUBLE,
  lookalike_perc_dmp_aa9bom9sdj6m_cpex DOUBLE,
  lookalike_target_dmp_aa9bqvteomrl_cpex INT,
  lookalike_target_dmp_aa9bom9sdj6m_cpex INT,
  a_score DOUBLE,
  b_score DOUBLE,
  c_score DOUBLE,
  d_score DOUBLE,
  e_score DOUBLE,
  a_perc DOUBLE,
  b_perc DOUBLE,
  c_perc DOUBLE,
  d_perc DOUBLE,
  e_perc DOUBLE,
  ad_interest_affinity_truck_drivers DOUBLE,
  ad_interest_affinity_womens_fashion DOUBLE,
  ad_interest_affinity_cosmetics DOUBLE,
  ad_interest_affinity_beer DOUBLE,
  ad_interest_affinity_black_friday DOUBLE,
  ad_interest_affinity_martial_arts DOUBLE,
  ad_interest_affinity_mortgage DOUBLE,
  ad_interest_affinity_skiing DOUBLE,
  ad_interest_affinity_mma DOUBLE)
USING delta
LOCATION '{path_to_fs}/fs.delta'
""")
display(res)

# COMMAND ----------

# MAGIC %md ###Metadata

# COMMAND ----------

res = spark.sql(f"""
CREATE TABLE IF NOT EXISTS hive_metastore.{database_name}.metadata (
  feature STRING,
  description STRING,
  extra MAP<STRING, STRING>,
  feature_template STRING,
  description_template STRING,
  category STRING,
  owner STRING,
  tags ARRAY<STRING>,
  start_date TIMESTAMP,
  frequency STRING,
  last_compute_date TIMESTAMP,
  dtype STRING,
  variable_type STRING,
  fillna_value STRING,
  fillna_value_type STRING,
  notebook_name STRING,
  notebook_absolute_path STRING,
  notebook_relative_path STRING,
  table STRING,
  backend STRING)
USING delta
LOCATION '{path_to_fs}/fs_metadata.delta'
""")
display(res)

# COMMAND ----------

# MAGIC %md ###Stage 1

# COMMAND ----------

res = spark.sql(f"""
CREATE TABLE IF NOT EXISTS hive_metastore.{database_name}.user_stage1 (
  user_id STRING,
  timestamp DATE,
  web_analytics_device_type_most_common_7d STRING,
  web_analytics_device_type_last_used_7d STRING,
  web_analytics_device_browser_most_common_7d STRING,
  web_analytics_device_browser_last_used_7d STRING,
  web_analytics_device_os_most_common_7d STRING,
  web_analytics_device_os_last_used_7d STRING,
  web_analytics_num_distinct_device_categories_7d BIGINT,
  web_analytics_channel_device_count_distinct_7d BIGINT,
  web_analytics_visit_time_most_common_7d STRING,
  web_analytics_mobile_user_7d DOUBLE,
  web_analytics_desktop_user_7d DOUBLE,
  web_analytics_smart_tv_user_7d DOUBLE,
  web_analytics_tablet_user_7d DOUBLE,
  web_analytics_time_on_site_avg_7d DOUBLE,
  web_analytics_web_active_7d INT,
  web_analytics_web_security_affinity_7d DOUBLE,
  web_analytics_page_search_engine_most_common_7d STRING,
  web_analytics_page_search_engine_last_used_7d STRING,
  web_analytics_pageviews_sum_7d BIGINT,
  owner_names_7d STRING,
  web_analytics_total_visits_7d BIGINT,
  web_analytics_blog_days_since_last_visit_7d INT,
  ad_interest_affinity_allergy DOUBLE,
  ad_interest_affinity_convertible DOUBLE,
  ad_interest_affinity_weight_loss DOUBLE,
  ad_interest_affinity_golf DOUBLE,
  ad_interest_affinity_clothing DOUBLE,
  ad_interest_affinity_remodeling_and_construction DOUBLE,
  ad_interest_affinity_photography DOUBLE,
  ad_interest_affinity_buying_or_selling_homes DOUBLE,
  ad_interest_affinity_asia DOUBLE,
  ad_interest_affinity_panic_or_anxiety_disorders DOUBLE,
  ad_interest_affinity_buying_or_selling_cars DOUBLE,
  ad_interest_affinity_motorcycles DOUBLE,
  ad_interest_affinity_elementary_school DOUBLE,
  ad_interest_affinity_pro_ice_hockey DOUBLE,
  ad_interest_affinity_australia_and_new_zealand DOUBLE,
  ad_interest_affinity_politics DOUBLE,
  ad_interest_affinity_video_and_computer_games DOUBLE,
  ad_interest_affinity_it_decision_makers DOUBLE,
  ad_interest_affinity_parenting DOUBLE,
  ad_interest_affinity_telecommuting DOUBLE,
  ad_interest_affinity_job_search DOUBLE,
  ad_interest_affinity_interior_decorating DOUBLE,
  ad_interest_affinity_high_school_students DOUBLE,
  ad_interest_affinity_pregnancy DOUBLE,
  ad_interest_affinity_animation DOUBLE,
  ad_interest_affinity_computer_reviews DOUBLE,
  ad_interest_affinity_traveling_with_kids DOUBLE,
  ad_interest_affinity_3_d_graphics DOUBLE,
  ad_interest_affinity_books_and_literature DOUBLE,
  ad_interest_affinity_board_games_or_puzzles DOUBLE,
  ad_interest_affinity_green_solutions DOUBLE,
  ad_interest_affinity_depression DOUBLE,
  ad_interest_affinity_gardening DOUBLE,
  ad_interest_affinity_cell_phones DOUBLE,
  ad_interest_affinity_college_life DOUBLE,
  ad_interest_affinity_local_news DOUBLE,
  ad_interest_affinity_financial_aid DOUBLE,
  ad_interest_affinity_guitar DOUBLE,
  ad_interest_affinity_canada DOUBLE,
  ad_interest_affinity_business_travel DOUBLE,
  ad_interest_affinity_insurance DOUBLE,
  ad_interest_affinity_south_america DOUBLE,
  ad_interest_affinity_performance_vehicles DOUBLE,
  ad_interest_affinity_agriculture DOUBLE,
  ad_interest_affinity_cigars DOUBLE,
  ad_interest_affinity_coffee_lovers DOUBLE,
  ad_interest_affinity_mens_health DOUBLE,
  ad_interest_affinity_dining_out DOUBLE,
  ad_interest_affinity_comic_books DOUBLE,
  ad_interest_affinity_mexico_and_central_america DOUBLE,
  ad_interest_affinity_hedge_fund DOUBLE,
  ad_interest_affinity_environmental_safety DOUBLE,
  ad_interest_affinity_humor DOUBLE,
  ad_interest_affinity_cold_and_flu DOUBLE,
  ad_interest_affinity_fashion DOUBLE,
  ad_interest_affinity_hr_software DOUBLE,
  ad_interest_affinity_financial_news DOUBLE,
  ad_interest_affinity_olympics DOUBLE,
  ad_interest_affinity_university_students DOUBLE,
  ad_interest_affinity_bodybuilding DOUBLE,
  ad_interest_affinity_generation_z DOUBLE,
  ad_interest_affinity_betting DOUBLE,
  ad_interest_affinity_astrology DOUBLE,
  ad_interest_affinity_teens DOUBLE,
  ad_interest_affinity_art_or_technology DOUBLE,
  ad_interest_affinity_fotovoltaics DOUBLE,
  ad_interest_affinity_dogs DOUBLE,
  ad_interest_affinity_fine_art DOUBLE,
  ad_interest_affinity_italy DOUBLE,
  ad_interest_affinity_cats DOUBLE,
  ad_interest_affinity_skateboarding DOUBLE,
  ad_interest_affinity_auto_parts DOUBLE,
  ad_interest_affinity_international_news DOUBLE,
  ad_interest_affinity_jewelry DOUBLE,
  ad_interest_affinity_advertising DOUBLE,
  ad_interest_affinity_diabetes DOUBLE,
  ad_interest_affinity_wine DOUBLE,
  ad_interest_affinity_b2b_small_and_midsize_business_osvc DOUBLE,
  ad_interest_affinity_weather DOUBLE,
  ad_interest_affinity_barbecues_and_grilling DOUBLE,
  ad_interest_affinity_vegan DOUBLE,
  ad_interest_affinity_energy_crisis DOUBLE,
  ad_interest_affinity_deal_hunters DOUBLE,
  ad_interest_affinity_christmas_shopping DOUBLE,
  ad_interest_affinity_trucks_and_accessories DOUBLE,
  ad_interest_affinity_movies DOUBLE,
  ad_interest_affinity_english_as_a_2nd_language DOUBLE,
  ad_interest_affinity_gay_life DOUBLE,
  ad_interest_affinity_cameras_and_camcorders DOUBLE,
  ad_interest_affinity_home_repair DOUBLE,
  ad_interest_affinity_radio DOUBLE,
  ad_interest_affinity_climbing DOUBLE,
  ad_interest_affinity_human_resources DOUBLE,
  ad_interest_affinity_music DOUBLE,
  ad_interest_affinity_celebrity_fan_or_gossip DOUBLE,
  ad_interest_affinity_football DOUBLE,
  ad_interest_affinity_exotic_pets DOUBLE,
  ad_interest_affinity_senior_living DOUBLE,
  ad_interest_affinity_data_centers DOUBLE,
  ad_interest_affinity_europe DOUBLE,
  ad_interest_affinity_usa DOUBLE,
  ad_interest_affinity_pro_basketball DOUBLE,
  ad_interest_affinity_mother_with_toddlers DOUBLE,
  ad_interest_affinity_credit_or_debt_and_loans DOUBLE,
  ad_interest_affinity_dating DOUBLE,
  ad_interest_affinity_electric_vehicle DOUBLE,
  ad_interest_affinity_internet_technology DOUBLE,
  ad_interest_affinity_b2b_big_corporations_managers_decision_makers DOUBLE,
  ad_interest_affinity_formule_1 DOUBLE,
  ad_interest_affinity_young_families_with_children DOUBLE,
  ad_interest_affinity_architects DOUBLE,
  ad_interest_affinity_boxing DOUBLE,
  ad_interest_affinity_womens_health DOUBLE,
  ad_interest_affinity_divorce_support DOUBLE,
  ad_interest_affinity_exotic_vacation DOUBLE,
  ad_interest_affinity_tattoos DOUBLE,
  ad_interest_affinity_luxury_vehicle DOUBLE,
  ad_interest_affinity_investments DOUBLE,
  ad_interest_affinity_middle_class_vehicle DOUBLE,
  ad_interest_affinity_suv_vehicle DOUBLE,
  ad_interest_affinity_eye_make_up DOUBLE,
  ad_interest_affinity_make_up DOUBLE,
  ad_interest_affinity_beauty DOUBLE,
  ad_interest_affinity_education DOUBLE,
  ad_interest_affinity_science DOUBLE,
  ad_interest_affinity_family_and_parenting DOUBLE,
  ad_interest_affinity_sports DOUBLE,
  ad_interest_affinity_careers DOUBLE,
  ad_interest_affinity_travel DOUBLE,
  ad_interest_affinity_real_estate DOUBLE,
  ad_interest_affinity_pets DOUBLE,
  ad_interest_affinity_society DOUBLE,
  ad_interest_affinity_shopping DOUBLE,
  ad_interest_affinity_home_and_garden DOUBLE,
  ad_interest_affinity_automotive DOUBLE,
  ad_interest_affinity_personal_finance DOUBLE,
  ad_interest_affinity_business DOUBLE,
  ad_interest_affinity_law_govt_and_politics DOUBLE,
  ad_interest_affinity_b2b DOUBLE,
  ad_interest_affinity_food_and_drink DOUBLE,
  ad_interest_affinity_health_and_fitness DOUBLE,
  ad_interest_affinity_arts_and_entertainment DOUBLE,
  ad_interest_affinity_hobbies_and_interests DOUBLE,
  ad_interest_affinity_style_and_fashion DOUBLE,
  ad_interest_affinity_technology_and_computing DOUBLE,
  ad_interest_affinity_news DOUBLE,
  ad_interest_affinity_home_tech_equipment DOUBLE,
  ad_interest_affinity_bathrooms DOUBLE,
  ad_interest_affinity_distillates DOUBLE,
  ad_interest_affinity_truck_drivers DOUBLE,
  ad_interest_affinity_womens_fashion DOUBLE,
  ad_interest_affinity_cosmetics DOUBLE,
  ad_interest_affinity_beer DOUBLE,
  ad_interest_affinity_black_friday DOUBLE,
  ad_interest_affinity_martial_arts DOUBLE,
  ad_interest_affinity_mortgage DOUBLE,
  ad_interest_affinity_skiing DOUBLE,
  ad_interest_affinity_mma DOUBLE)
USING delta
LOCATION '{path_to_fs}/fs_user_stage1.delta'
""")
display(res)

# COMMAND ----------

# MAGIC %md ###Stage 2

# COMMAND ----------

res = spark.sql(f"""
CREATE TABLE IF NOT EXISTS hive_metastore.{database_name}.user_stage2 (
  user_id STRING,
  timestamp TIMESTAMP,
  income_model_score_low DOUBLE,
  income_model_score_mid DOUBLE,
  income_model_score_high DOUBLE,
  income_model_perc_low DOUBLE,
  income_model_perc_mid DOUBLE,
  income_model_perc_high DOUBLE,
  edu_model_score_zs DOUBLE,
  edu_model_score_ss_no DOUBLE,
  edu_model_score_ss_yes DOUBLE,
  edu_model_score_vs DOUBLE,
  edu_model_perc_zs DOUBLE,
  edu_model_perc_ss_no DOUBLE,
  edu_model_perc_ss_yes DOUBLE,
  edu_model_perc_vs DOUBLE,
  sociodemo_prob_agegroup_0_17 DOUBLE,
  sociodemo_perc_agegroup_0_17 DOUBLE,
  sociodemo_prob_agegroup_18_24 DOUBLE,
  sociodemo_perc_agegroup_18_24 DOUBLE,
  sociodemo_prob_agegroup_25_34 DOUBLE,
  sociodemo_perc_agegroup_25_34 DOUBLE,
  sociodemo_prob_agegroup_35_44 DOUBLE,
  sociodemo_perc_agegroup_35_44 DOUBLE,
  sociodemo_prob_agegroup_45_54 DOUBLE,
  sociodemo_perc_agegroup_45_54 DOUBLE,
  sociodemo_prob_agegroup_55_64 DOUBLE,
  sociodemo_perc_agegroup_55_64 DOUBLE,
  sociodemo_prob_agegroup_65_100 DOUBLE,
  sociodemo_perc_agegroup_65_100 DOUBLE,
  sociodemo_prob_gender_male DOUBLE,
  sociodemo_perc_gender_male DOUBLE,
  sociodemo_perc_gender_female DOUBLE,
  sociodemo_prob_gender_female DOUBLE,
  sociodemo_targets_age STRING,
  sociodemo_targets_gender STRING,
  lookalike_targets STRING,
  lookalike_prob_dmp_aa9bqvteomrl_cpex DOUBLE,
  lookalike_perc_dmp_aa9bqvteomrl_cpex DOUBLE,
  lookalike_prob_dmp_aa9bom9sdj6m_cpex DOUBLE,
  lookalike_perc_dmp_aa9bom9sdj6m_cpex DOUBLE,
  lookalike_target_dmp_aa9bqvteomrl_cpex INT,
  lookalike_target_dmp_aa9bom9sdj6m_cpex INT)
USING delta
LOCATION '{path_to_fs}/fs_user_stage2.delta'
""")
display(res)

# COMMAND ----------

# MAGIC %md ###Stage 3

# COMMAND ----------

res = spark.sql(f"""
CREATE TABLE IF NOT EXISTS hive_metastore.{database_name}.user_stage3 (
  user_id STRING,
  timestamp TIMESTAMP,
  a_score DOUBLE,
  b_score DOUBLE,
  c_score DOUBLE,
  d_score DOUBLE,
  e_score DOUBLE,
  a_perc DOUBLE,
  b_perc DOUBLE,
  c_perc DOUBLE,
  d_perc DOUBLE,
  e_perc DOUBLE)
USING delta
LOCATION '{path_to_fs}/fs_user_stage3.delta'
""")
display(res)

# COMMAND ----------

# MAGIC %md ###User

# COMMAND ----------

res = spark.sql(f"""
CREATE TABLE spark_catalog.{database_name}.user (
  user_id STRING,
  timestamp DATE,
  ad_interest_affinity_education DOUBLE,
  ad_interest_affinity_science DOUBLE,
  ad_interest_affinity_family_and_parenting DOUBLE,
  ad_interest_affinity_sports DOUBLE,
  ad_interest_affinity_careers DOUBLE,
  ad_interest_affinity_travel DOUBLE,
  ad_interest_affinity_real_estate DOUBLE,
  ad_interest_affinity_pets DOUBLE,
  ad_interest_affinity_society DOUBLE,
  ad_interest_affinity_shopping DOUBLE,
  ad_interest_affinity_home_and_garden DOUBLE,
  ad_interest_affinity_automotive DOUBLE,
  ad_interest_affinity_personal_finance DOUBLE,
  ad_interest_affinity_business DOUBLE,
  ad_interest_affinity_b2b DOUBLE,
  ad_interest_affinity_law_govt_and_politics DOUBLE,
  ad_interest_affinity_food_and_drink DOUBLE,
  ad_interest_affinity_health_and_fitness DOUBLE,
  ad_interest_affinity_arts_and_entertainment DOUBLE,
  ad_interest_affinity_hobbies_and_interests DOUBLE,
  ad_interest_affinity_style_and_fashion DOUBLE,
  ad_interest_affinity_technology_and_computing DOUBLE,
  ad_interest_affinity_news DOUBLE)
USING delta
LOCATION '{path_to_fs}/user.delta'
""")
display(res)
