name: test-action
on:
  push:
    branches:
      - github_actions_branch

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: rickstaa/action-black@v1
