name: black-formatter
run-name: Triggered by @${{ github.actor }}
on:
  push:
    branches:
      - github_actions_branch

jobs:
  black:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
