name: black-formatter
run-name: Check code format merged by @${{ github.actor }}
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  black:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
