name: Deploy all new jobs
on: 
  push:
    branches:
      - main
    paths:
      - jobs

jobs:
  # Deploy all jobs that are located in specific folder
  deploy:
    name: Deployment into DBX
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      COMMIT_HASH: "${{ github.sha }}"
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      # - name: set up Python 3
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.11.3'

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Setup Databricks CLI access
        run: |
          echo -e "[DEFAULT]\nhost = $DBX_HOST\ntoken = $DBX_ACCESS_TOKEN" > ~/.databrickscfg
        env:
          DBX_HOST: ${{ secrets.dev_dbx_host }}
          DBX_ACCESS_TOKEN: ${{ secrets.dev_dbx_access_token }}

      - name: Deploy new jobs
        run: |
          # TBD - only one file per job run
          # check folder for changes to FIND IT
    
