name: Pylint and black formatting check

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited]

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # specify necessary python version(s)
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r .\init\requirements_pylint.txt
        pip install pylint
    - name: Analysing the code with pylint
      # list all files and use pylint on them
      run: |
        pylint $(git ls-files '*.py')
      # list all files that were changed and use pylint on them
      # run: |
      #   pylint $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})  
  # check formatting and force it if it's not done properly
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        continue-on-error: true  # we do only check without necesity to have positive result
        with:
          options: "--check --verbose"
          src: "."
