name: Testing DBX configuration

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited]

jobs:
  # format every Python file using 'black' formatting - shouldn't be necessary but to keep it nice
  black:
    name: Black formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--verbose"
          src: "."
          version: "23.10.1"

  # update repository on DBX workspace
  deploy:
    name: Deployment into DBX
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      COMMIT_HASH: "${{ github.sha }}"
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Setup Databricks CLI access for DEV workspace
        run: |
          echo -e "[DEFAULT]\nhost = $DBX_HOST\ntoken = $DBX_ACCESS_TOKEN" > ~/.databrickscfg
        env:
          DBX_HOST: ${{ secrets.DBX_ACCESS_TOKEN_DEV }}
          DBX_ACCESS_TOKEN: ${{ secrets.DBX_HOST_DEV }}
      # instead of path to the repo '/Repos/adpicker-cpex-odap/develop' has to be 'repo_id' - 3844953836266953
      - name: Get ~/.databrickscfg content
        run: |
          echo "$(cat ~/.databrickscfg)"
      - name: Get configuration
        run: |
          databricks auth profiles
      - name: Get repos list
        run: |
          databricks repos list
      - name: Get jobs list
        run: |
          databricks jobs list
      - name: Update adpicker repo 'adpicker-cpex-odap' with branch 'develop'
        run: |
          databricks repos update 3844953836266953 --branch develop
